config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}
  devise_scope :user do 
    get '/login', to: 'devise/sessions#new', as: 'login'
    get '/signup', to: 'devise/registrations#new', as: 'signup'
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end 

  resources :properties
  resources :locations, only: [:index, :show] do 
    resources :properties, only: [:show, :new]
  end 

  
  
  root to: "application#welcome"
end

app/models/amenity.rb
class Amenity < ApplicationRecord
    has_many :property_amenities
    has_many :properties, through: :property_amenities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :properties
    has_many :users, through: :properties 
    validates :name, presence: true 
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :location
    belongs_to :user
    has_many :property_amenities
    has_many :amenities, through: :property_amenities
    has_one_attached :avatar
    scope :latest, -> { order created_at: :desc}
    scope :local, -> (locationid) { where(location_id: locationid)}
    accepts_nested_attributes_for :location, :reject_if => lambda { |a| a[:name].blank? || a[:state].blank? }, :allow_destroy => true
    accepts_nested_attributes_for :amenities, :reject_if => lambda { |a| a[:name].blank? }
    validates :name, presence: true 
    validates :bedrooms, presence: true
    validates :bathrooms, presence: true

    def self.search(search)
        location = Location.find_by(name: search) 
        if location 
            @properties = Property.where(location_id: location.id)
        end
    end 

  

end

app/models/property_amenity.rb
class PropertyAmenity < ApplicationRecord
    belongs_to :property 
    belongs_to :amenity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: [:github, :google_oauth2], authentication_keys: [:login]
  has_many :properties
  has_many :locations, through: :properties
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  attr_writer :login

  def login
    @login || self.username || self.email
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
    user.username = provider_data.info.name
    user.email = provider_data.info.email
    user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new,:create,:destroy]
   
    def welcome
      if user_signed_in? 
        redirect_to properties_path
      end
    end 

    private 

    def redirect 
      if !user_signed_in? 
        redirect_to '/'
      end 
    end 

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController 

    def github
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
            flash[:notice] = "Congratulations, you're signed up!"
        else
            flash[:error] = 'There was a problem.'
            redirect_to new_user_registration_path
        end
    end

    def google_oauth2
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
            flash[:notice] = "Congratulations, you're signed up!"
        else
            flash[:error] = 'There was a problem.'
            redirect_to new_user_registration_path
        end
    end
    def failure
        flash[:error] = 'There was a problem'
        redirect_to new_user_registration_path        
    end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :redirect

    def index  
        @locations = current_user.locations.uniq
    end 

    def show  
        @location = current_user.locations.find_by(id: params[:id])
        if !@location 
            flash[:error]  = "I'm sorry, you don't have access to view that page."
            redirect_to properties_path
        else 
            @properties = Property.local(params[:id])
            render :show 
        end 
    end 
   
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :redirect
    before_action :set_property, only: [:show, :edit, :update, :destroy]
    
    def index
        if params[:search]
            @properties = Property.search(params[:search])
        else  
            @properties = current_user.properties
        end
    end 

    def new 
        @property = Property.new(location_id: params[:location_id]) 
        @amenitites = Amenity.all 
    end 

    def create 
        @property = current_user.properties.build(property_params)
        if @property.save 
            redirect_to property_path(@property)
        else  
            render :new
        end
    end 

    def show
    end

    def edit 
    end 

    def update
        if @property.update(property_params)
            redirect_to property_path(@property)
        else 
            render :edit
        end 
    end

    def destroy 
        @property.destroy
        redirect_to properties_path
    end 


    private 

    def set_property 
        @property = current_user.properties.find_by(id: params[:id])
        if !@property
            flash[:error]  = "I'm sorry, you don't have access to view that page."
            redirect_to properties_path
        end 
    end
    
    def property_params 
        params.require(:property).permit(
            :search,
            :name, 
            :user_id, 
            :location_id, 
            :bedrooms, 
            :bathrooms, 
            :available,
            :avatar,
            amenity_ids: [], 
            location_attributes: [ 
                :name, 
                :state
            ],
            amenities_attributes: [ 
                :name, 
            ]
        )
    end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private 
    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 

    def account_update 
        params.require(:user).permit(:username, :email, :password, :password_confirmation) 
    end 

end 

app/helpers/application_helper.rb
module ApplicationHelper

end

 

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/application/welcome.html.erb
<div class ="center">
    <h1>Vacation Homes Management</h1>
    <h2>An easy way to manage your vaction properties near and far</h2>
   
    <% if user_signed_in? %>
    <h4><%= link_to "View Your Properties", properties_path %></h4>
    <% else %>
    <h4><%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Login", new_user_session_path %> to begin managing your homes</h4>
    <% end%>
    </div>
    <%=image_tag("cabin_in_woods.jpg") %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
   <div class="navbar-nav">
    <div class="form-inline">
    <% if !user_signed_in? %>
      <a class="nav-item nav-link" href="/signup">Signup</a>
      <a class="nav-item nav-link" href="/login">Login</a>
    <% else  %>
        <a class="nav-item nav-link" href="/"> Welcome, <%= current_user.username %>  </a>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/locations" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Locations
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% current_user.locations.each do |location| %>
            <a class="dropdown-item" href="/locations/<%= location.id %>"><%= location.name %></a>
            <%end%>
          </div>
        </li>
        <a class="nav-item nav-link" href="/properties/new"> Add New Property</a>
       <a class="nav-item nav-link" href="/logout">Logout</a>
    <% end%>
    </div>
  </div>
</nav>
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VacationHomesManagerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="assets/stylesheets/application.css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

      <style>
      @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400&display=swap');
      </style>

      <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
      </style>
    <%= render 'layouts/nav' %>
  </head>
  
  <body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <div class="margin">
     <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Your property locations: </h1>
    <% @locations.each do |location| %>
    <ul>
    <div class="center">
    <h2><%=link_to location.name, location_path(location) %></h3>
    </ul>
    </div>
    <% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %>, <%= @location.state %> </h1>
    
    <div class="center">
    <button><%= link_to "Add new property to this location", new_location_property_path(@location) %></button>
    </div>

<br>
<br>

    <div class="container">
        <div class="row row-cols-3">
         <% @properties.each do |property| %>
            <div class="card" style="width: 25rem;">
            <% if property.avatar.attached? %>
                <img src="<%= (url_for(property.avatar)) %>" class="card-img-top" alt="...">
            <% end %>

            <div class="card-body">
            <h1 class="card-title"><%= link_to property.name, location_property_path(property.location, property) %></h1>
            <h2 class="card-text">
            Bedrooms: <%= property.bedrooms %> 
            <br>
            Bathrooms: <%= property.bathrooms %>
            <br>

            Amenities: </h2>
            <% property.amenities.each do |amenity|%>
            <h3><li><%= amenity.name %></li> </h3>
            <% end %></p>
            <button><%= link_to "View Property", location_property_path(property.location, property) %></button>
            </div>
        </div>
        <% end %>
        </div>
    </div>
<br>

    

   

app/views/properties/_form.html.erb
<%= form_for property do |f| %>
    <div class= "form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %> <br>
    </div>
   
     <div class= "form-group">
    <%= f.label "Photo" %>
    <%= f.file_field :avatar, class: "form-control" %> <br>
    </div>
    
    <% if property.location_id.nil? %>

    <div class="form-group">
    <h3>Choose from an existing location: </h3> 
    <%= f.collection_select :location_id, Location.all, :id, :name, :include_blank => true, class: "form-control"  %> <br>
    <br>

        <%= f.fields_for :location, Location.new do |p_location| %> <br>
            <h3> Or create a new location: </h3> 
            <div class= "form-group">
                <div class="row">
                    <div class="col">
                    <%= p_location.label "City" %>
                    <%= p_location.text_field :name, class:"form-control" %> <br> <br>
                    </div>
                    <div class="col">
                    <%= p_location.label :state %>
                    <%= p_location.text_field :state, class:"form-control" %> <br> <br>
                    </div>
                </div>
            </div>
        <% end %>
    <% else %>
    <%= f.hidden_field :location_id %>
    <%end%>

    <div class= "form-group">
    <%= f.label :bedrooms %>
    <%= f.number_field :bedrooms, class: "form-control" %> <br>
    </div>

    <div class= "form-group">
    <%= f.label :bathrooms %>
    <%= f.number_field :bathrooms, class: "form-control" %> <br>
     </div>

    <%= f.label "Amenities:" %>
   
    <%= f.collection_check_boxes(:amenity_ids, Amenity.all, :id, :name) do |a| %>
            <%= a.label class:"label-checkbox" do%>
            <%=a.check_box + a.text%>
        <%end%>
    <% end %>
     <%= f.fields_for :amenities, Amenity.new do |p_amenity| %> <br>
            <h3> Or create a new amenity: </h3> 
            <div class= "form-group">
                <div class="row">
                    <div class="col">
                    <%= p_amenity.label :name %>
                    <%= p_amenity.text_field :name, class:"form-control" %> 
                    </div>
                </div>
            </div>
        <% end %>
    <%= f.label :available %>
    <%= f.check_box :available %> <br>

    <%= f.submit @property.persisted? ? "Update Property" : "Add Property" %>
<% end %>

app/views/properties/edit.html.erb
<% if @property.errors.full_messages.any? %>
    <% @property.errors.full_messages.each do |error_message| %>
        <%= error_message if @property.errors.full_messages.first == error_message %> <br />
    <% end %>
<% end %>

<h1>Update property</h1>
<div class="margin">
<%= render partial: "form", locals: {property: @property} %>
</div>
<br>
<br>
<br>

app/views/properties/index.html.erb
<%= form_tag properties_path, method: :get do %>
  <%= label_tag  "Search for a location name:" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<h1> Your vacation properties </h1>
<div class="container">
     <div class="row row-cols-3">
            <% @properties.each do |p|%>
            <div class="card" style="width: 22rem;">
            <% if p.avatar.attached? %>
            <img src="<%= (url_for(p.avatar)) %>" class="card-img-top" alt="...">
            <% end %>
            <div class="card-body">
            
            
                <h2 class="card-title"><%= p.name %></h2>
                <h3 class="card-subtitle mb-2 text-muted"><%= link_to p.location.name , location_path(p.location) %>, <%= p.location.state%> </h3>
                <h3 class="card-text">
                    Bedrooms: <%= p.bedrooms %></p>
                    Bathrooms: <%= p.bathrooms %></p>
                    Amenities: 
                    <% p.amenities.each do |amenity|%>
                    <p><li> <%= amenity.name %></li></p>
                    <% end %></p>
                    <% if p.available? %>
                        Available 
                    <% end %>
                <br>
                <br>
                <button><%= link_to "Edit Property", edit_property_path(p) %></button>
                <button><%= link_to "View Property", property_path(p) %></button>
            </div>
        </div>
    <% end %>
    </div>
   
<br> 
<br>
    <button type="button" class="btn btn-secondary btn-lg btn-block"><a class="text-my-own-color" href="/properties/new">Add a new property</a></button>
    <button type="button" class="btn btn-secondary btn-lg btn-block"><a class="text-my-own-color" href="/locations">View all property locations</a></button>

app/views/properties/new.html.erb
<body>
    
        <% if @property.errors.any? %>
        <div class="error-message">
                <% @property.errors.full_messages.each do |error_message| %>
                <span class="error-text"><%=error_message%> </span>
            <% end %>
        <% end %>
        </div>
    </div>
<br>
        <h1>Add a new property</h1>
        <div class="margin">
        <%= render partial: "form", locals: {property: @property} %>
        </div>
    </div>
 <br>
</body>

app/views/properties/show.html.erb
<h1><%= @property.name %> <br></h1>

    <% if @property.avatar.attached? %>
        <image src="<%= (url_for(@property.avatar)) %>">
    <% end %>
    
    <h2><%= @property.location.name %>, <%= @property.location.state %></h2>
    <h3>Bedrooms: <%= @property.bedrooms %> <br></h3>
    <h3>Bathrooms: <%= @property.bathrooms %> <br></h3>
    <h3>Amenities:</h3>
    <% @property.amenities.each do |amenity| %>
       <p>  <li> <%= amenity.name %> </li> </p>
     <% end %>

<button><%= link_to "Edit Property", edit_property_path(@property) %></button>
<button><%= link_to "Delete Property", @property, method: :delete, data: { confirm: 'Are you sure?' }%></button>
<button><%= link_to "Return to home", properties_path %></button>